### PR TITLE
Clean up test vectors for v1

### PR DESCRIPTION
**Pull request by thunderbiscuit**
This PR will update the test vectors to bring them in line with the new APIs.

These are built out of my [cashu-client]() library and partially stolen from the [nutshell](https://github.com/cashubtc/nutshell) library, and I think we should make sure they pass for at least a few implementations before considering merging (i.e. I don't trust my code just yet!). But I figured I'd get the ball rolling. Let me know if you'd like to add more test cases.

- [x] NUT-00
- [x] NUT-01
- [x] NUT-02

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
I added and will maintain a separate test class in my library for tests in the NUTs. Some of them repeat other tests that are scattered throughout the test suite but this makes them easy to find for others and easy to maintain for myself against the spec tests.

Commit: https://github.com/thunderbiscuit/cashu-client/pull/2/commits/bed35c11e140e00cba1563829812cae5346b8869

**Review by callebtc — APPROVED** [review]

**Comment by thunderbiscuit** [comment]
This is ready for a final review/merge IMO. Friendly bump.

**Review by thesimplekid — APPROVED** [review]
ACK https://github.com/cashubtc/nuts/pull/67/commits/05fd8df0a572a8f8e1baa08950af1bfa6cf8830e. All are implemented and working in [cashu-crab](https://github.com/thesimplekid/cashu-crab)

**Comment by callebtc** [comment]
*chefs kiss* a PR like this deserves a prize

**Pull request merged**
